version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./resources:/app/resources  # Mount parent resources directory
    environment:
      - PYTHONUNBUFFERED=1  # For better logging
    restart: unless-stopped

networks:
  tenders-network:
    driver: bridge