version: '3.8'

services:
  api:
    build:
      context: .
      target: runtime
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./resources:/app/resources
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 30G
    networks:
      - tenders-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: production
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:8001
      - REACT_APP_IN_DOCKER=true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - tenders-network
    restart: unless-stopped


networks:
  tenders-network:
    driver: bridge